(()=>{
'use strict';
const DB='pdf-prepisovac-local';const VER=1;const STORE='documents';let dbP=null;let restoring=false;
const $=s=>document.querySelector(s);
function openDB(){if(dbP)return dbP;dbP=new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('savedAt','savedAt')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbP}
function tx(mode,fn){return openDB().then(db=>new Promise((res,rej)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE);let out;try{out=fn(s)}catch(e){rej(e);return}t.oncomplete=()=>res(out);t.onerror=()=>rej(t.error)}))}
async function allDocs(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res((r.result||[]).sort((a,b)=>b.savedAt-a.savedAt));r.onerror=()=>rej(r.error)})}
async function saveFile(file){
  if(!file||restoring)return;
  try{
    const docs=await allDocs();const same=docs.find(d=>d.name===file.name&&d.size===file.size&&d.lastModified===file.lastModified);
    const rec={id:same?.id||crypto.randomUUID(),name:file.name||'dokument',type:file.type||'application/octet-stream',size:file.size,lastModified:file.lastModified||Date.now(),savedAt:Date.now(),blob:file};
    await tx('readwrite',s=>s.put(rec));await askPersistent();updateBadge();
  }catch(e){console.warn('Local save failed',e)}
}
async function askPersistent(){try{if(!navigator.storage?.persist)return;const already=await navigator.storage.persisted?.();if(!already)await navigator.storage.persist()}catch{}}
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' kB';return(n/1048576).toFixed(n>10485760?0:1)+' MB'}
function date(t){try{return new Intl.DateTimeFormat('cs',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(t))}catch{return''}}
function icon(d){return d.type?.startsWith('image/')?'🖼️':'📄'}
async function openDoc(id){const db=await openDB();const rec=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(!rec)return;const input=$('#fileInput');if(!input)return;const f=new File([rec.blob],rec.name,{type:rec.type,lastModified:rec.lastModified});const dt=new DataTransfer();dt.items.add(f);restoring=true;input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));restoring=false;closeLibrary()}
async function del(id){await tx('readwrite',s=>s.delete(id));render();updateBadge()}
async function clearAll(){if(!confirm('Smazat všechny lokálně uložené dokumenty z tohoto telefonu?'))return;await tx('readwrite',s=>s.clear());render();updateBadge()}
function addStyle(){if($('#libraryStyle'))return;const st=document.createElement('style');st.id='libraryStyle';st.textContent=`
  .libSheet{position:fixed;inset:0;z-index:260;background:#0008;display:flex;align-items:flex-end;justify-content:center}.libSheet.hidden{display:none!important}.libCard{width:min(760px,100%);max-height:86dvh;overflow:auto;background:#fff;border-radius:22px 22px 0 0;padding:14px;padding-bottom:calc(16px + env(safe-area-inset-bottom));box-shadow:0 -10px 40px #0004}.libHead{position:sticky;top:-14px;background:#fff;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:12px 0 8px}.libList{display:grid;gap:8px}.libItem{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;border:1px solid var(--line);border-radius:13px;padding:9px;background:#fff}.libIcon{font-size:25px}.libName{font-weight:800;font-size:13px;word-break:break-word}.libMeta{font-size:10px;color:var(--muted);margin-top:2px}.libActions{display:flex;gap:5px}.libActions button{min-height:38px!important;padding:7px 9px!important}.libInfo{font-size:11px;color:var(--muted);background:#f3f6f7;border-radius:11px;padding:9px;margin:8px 0}.libEmpty{text-align:center;color:var(--muted);padding:30px 10px}.libCount{font-size:10px;padding:3px 7px;border-radius:999px;background:#155873;color:#fff;margin-left:4px}
  @media(max-width:640px){.libCard{max-height:80dvh;border-radius:17px 17px 0 0;padding:10px}.libItem{grid-template-columns:auto 1fr}.libActions{grid-column:1/-1}.libActions button:first-child{flex:1}.libActions button{min-height:42px!important}}
`;document.head.appendChild(st)}
function build(){if($('#localLibrary'))return;addStyle();const d=document.createElement('div');d.id='localLibrary';d.className='libSheet hidden';d.innerHTML=`<div class="libCard"><div class="libHead"><div><b>💾 Moje dokumenty</b><span id="libCount" class="libCount">0</span></div><button id="libClose" class="ghost">✕</button></div><div id="libStorage" class="libInfo">Dokumenty jsou uložené pouze lokálně v tomto telefonu/prohlížeči.</div><div id="libList" class="libList"></div><div class="row" style="margin-top:10px"><button id="libClear" class="danger">Smazat vše</button></div></div>`;document.body.appendChild(d);$('#libClose').onclick=closeLibrary;d.addEventListener('click',e=>{if(e.target===d)closeLibrary()});$('#libClear').onclick=clearAll}
async function storageText(){try{const e=await navigator.storage?.estimate?.();if(!e)return'Dokumenty jsou uložené pouze lokálně v tomto telefonu/prohlížeči.';const p=await navigator.storage.persisted?.();return`Lokální úložiště: ${fmt(e.usage||0)} použito z přibližně ${fmt(e.quota||0)}. ${p?'Trvalé úložiště povoleno. ✅':'Prohlížeč může data při velkém nedostatku místa odstranit.'}`}catch{return'Dokumenty jsou uložené pouze lokálně v tomto telefonu/prohlížeči.'}}
async function render(){build();const docs=await allDocs();$('#libCount').textContent=String(docs.length);$('#libStorage').textContent=await storageText();const list=$('#libList');list.innerHTML=docs.length?docs.map(d=>`<div class="libItem"><div class="libIcon">${icon(d)}</div><div><div class="libName"></div><div class="libMeta">${fmt(d.size)} • ${date(d.savedAt)}</div></div><div class="libActions"><button class="primary libOpen" data-id="${d.id}">Otevřít</button><button class="danger libDel" data-id="${d.id}">Smazat</button></div></div>`).join(''):'<div class="libEmpty">Zatím tu nic není. Každý nově nahraný PDF nebo obrázek se sem automaticky uloží.</div>';[...list.querySelectorAll('.libItem')].forEach((row,i)=>{row.querySelector('.libName').textContent=docs[i].name});list.querySelectorAll('.libOpen').forEach(b=>b.onclick=()=>openDoc(b.dataset.id));list.querySelectorAll('.libDel').forEach(b=>b.onclick=()=>del(b.dataset.id))}
async function updateBadge(){const docs=await allDocs().catch(()=>[]);const b=$('#libraryBtn .libCount');if(b)b.textContent=String(docs.length)}
function openLibrary(){build();$('#localLibrary').classList.remove('hidden');document.body.style.overflow='hidden';render()}
function closeLibrary(){$('#localLibrary')?.classList.add('hidden');document.body.style.overflow=''}
function addButton(){if($('#libraryBtn'))return;const row=$('#startCard .row');if(!row)return;const b=document.createElement('button');b.id='libraryBtn';b.type='button';b.className='btn ghost';b.innerHTML='💾 Moje dokumenty <span class="libCount">0</span>';b.onclick=openLibrary;row.appendChild(b);updateBadge()}
function init(){build();addButton();const input=$('#fileInput');if(input)input.addEventListener('change',e=>{const f=e.target.files?.[0];if(f&&!restoring)saveFile(f)},true);askPersistent()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();