(()=>{
'use strict';
const $=s=>document.querySelector(s);let sheet,list,thumbUrls=[],busy=false;
const B=()=>window.PDFPBridge;
function blobCanvas(blob){return new Promise((res,rej)=>{const u=URL.createObjectURL(blob),im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);URL.revokeObjectURL(u);res(c)};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u})}
const toBlob=(c,q=.94)=>new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Export stránky selhal')),'image/jpeg',q));
function revoke(){thumbUrls.forEach(URL.revokeObjectURL);thumbUrls=[]}
function addStyle(){if($('#pageToolsStyle'))return;const s=document.createElement('style');s.id='pageToolsStyle';s.textContent=`
.pageToolsSheet{position:fixed;inset:0;z-index:300;background:#0008;display:flex;align-items:flex-end;justify-content:center}.pageToolsSheet.hidden{display:none!important}.pageToolsCard{width:min(820px,100%);max-height:92dvh;overflow:auto;background:#f7f9fa;border-radius:22px 22px 0 0;padding:12px 12px calc(16px + env(safe-area-inset-bottom));box-shadow:0 -12px 40px #0004}.pageToolsHead{position:sticky;top:-12px;z-index:5;background:#f7f9fa;display:flex;align-items:center;justify-content:space-between;padding:10px 0}.pageToolsHead h2{margin:0;font-size:18px}.pageAdd{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:5px 0 10px}.pageAdd button{min-height:47px}.pageList{display:grid;gap:8px}.pageRow{display:grid;grid-template-columns:64px minmax(0,1fr) auto;gap:8px;align-items:center;background:#fff;border:1px solid var(--line);border-radius:13px;padding:7px}.pageRow.current{outline:2px solid #0b789555}.pageThumb{width:64px;height:84px;background:#e1e5e7;border-radius:7px;overflow:hidden;display:flex;align-items:center;justify-content:center}.pageThumb img{width:100%;height:100%;object-fit:contain}.pageInfo b{font-size:12px}.pageInfo div{font-size:10px;color:var(--muted);margin-top:2px}.pageBtns{display:grid;grid-template-columns:repeat(2,42px);gap:3px}.pageBtns button{min-height:38px!important;padding:4px!important}.pageSmart{margin-top:10px;background:#fff;border:1px solid var(--line);border-radius:14px;padding:10px}.pageSmart h3{margin:0 0 8px;font-size:14px}.pageSmartGrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.pageSmartGrid button,.pageSmartGrid select{min-height:44px}.pageWarn{font-size:10px;color:var(--muted);margin-top:7px;line-height:1.35}.pageProgress{font-size:11px;color:#155873;min-height:18px;margin-top:6px;text-align:center}
@media(max-width:640px){.pageToolsCard{max-height:94dvh;border-radius:18px 18px 0 0;padding:9px}.pageRow{grid-template-columns:58px minmax(0,1fr) 88px}.pageThumb{width:58px;height:76px}.pageBtns{grid-template-columns:repeat(2,41px)}.pageSmartGrid{grid-template-columns:1fr}.pageAdd{position:sticky;top:45px;z-index:4;background:#f7f9fa;padding:4px 0}.pageSmart{padding:8px}}
`;document.head.appendChild(s)}
function build(){if(sheet)return;addStyle();sheet=document.createElement('div');sheet.id='pageTools';sheet.className='pageToolsSheet hidden';sheet.innerHTML=`<div class="pageToolsCard"><div class="pageToolsHead"><h2>🗂 Správa stránek</h2><button id="pageToolsClose" class="ghost">✕</button></div><div class="pageAdd"><button id="pageAddFiles" class="primary">＋ Přidat obrázek / PDF</button><button id="pageGoCurrent">▶ Zpět do dokumentu</button></div><input id="pageFiles" type="file" accept="image/*,application/pdf" multiple hidden><div id="pageList" class="pageList"></div><div class="pageSmart"><h3>✨ Úprava skenů</h3><div class="pageSmartGrid"><button id="pageAutoCrop">✂ Auto ořez aktuální</button><button id="pageDeskew">📐 Automaticky narovnat</button><select id="pageStyleRef" aria-label="Vzorová stránka"></select><button id="pageMatchAll">🎨 Sjednotit ostatní podle vzoru</button></div><div class="pageWarn">Otočení, ořez a narovnání mění geometrii stránky, proto u té stránky resetují OCR a textové úpravy. Sjednocení barev geometrii nemění.</div><div id="pageProgress" class="pageProgress"></div></div></div>`;document.body.appendChild(sheet);list=$('#pageList');$('#pageToolsClose').onclick=close;sheet.addEventListener('click',e=>{if(e.target===sheet)close()});$('#pageAddFiles').onclick=()=>$('#pageFiles').click();$('#pageFiles').onchange=e=>{addFiles([...e.target.files]);e.target.value=''};$('#pageGoCurrent').onclick=()=>{close();showEditor()};$('#pageAutoCrop').onclick=()=>smartCrop(B().summary().page);$('#pageDeskew').onclick=()=>deskew(B().summary().page);$('#pageMatchAll').onclick=matchAll}
function showEditor(){$('#startCard')?.scrollIntoView({block:'start'});$('#editor')?.classList.remove('hidden');setTimeout(()=>$('#canvasWrap')?.scrollIntoView({block:'center'}),60)}
async function render(){build();if(!B()?.hasDocument()){list.innerHTML='<div class="pageWarn">Nejdřív otevři dokument nebo projekt.</div>';return}revoke();const meta=B().pageMeta(),blobs=await B().pageThumbs();list.innerHTML='';const ref=$('#pageStyleRef');ref.innerHTML='';meta.forEach((m,i)=>{const u=URL.createObjectURL(blobs[i]);thumbUrls.push(u);const r=document.createElement('div');r.className='pageRow'+(m.current?' current':'');r.innerHTML=`<div class="pageThumb"><img src="${u}"></div><div class="pageInfo"><b>Strana ${i+1}</b><div>${m.width}×${m.height}px</div><div>${m.ocrDone?'OCR hotovo':'bez OCR'} • ${m.edits} úprav</div></div><div class="pageBtns"><button data-a="up" ${i===0?'disabled':''}>↑</button><button data-a="down" ${i===meta.length-1?'disabled':''}>↓</button><button data-a="rot">↻</button><button data-a="del" class="danger">×</button></div>`;r.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{const a=b.dataset.a;if(a==='up')B().movePage(i,i-1);if(a==='down')B().movePage(i,i+1);if(a==='rot'){if((m.ocrDone||m.edits)&&!confirm('Otočení resetuje OCR a textové úpravy této stránky. Pokračovat?'))return;B().rotatePage(i,90)}if(a==='del'){if(!confirm(`Smazat stranu ${i+1}?`))return;try{B().deletePage(i)}catch(e){alert(e.message)}}await render()});r.querySelector('.pageThumb').onclick=()=>{B().setPage(i);render()};list.appendChild(r);const o=document.createElement('option');o.value=i;o.textContent=`Vzor: strana ${i+1}`;ref.appendChild(o)});ref.value=String(Math.max(0,meta.findIndex(x=>x.current)))}
async function addFiles(files){if(!files.length||busy)return;busy=true;progress('Přidávám stránky…');try{const blobs=[];for(const f of files){if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')){const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;for(let n=1;n<=pdf.numPages;n++){progress(`PDF: strana ${n}/${pdf.numPages}…`);const pg=await pdf.getPage(n),vp=pg.getViewport({scale:2}),scale=Math.min(1,2200/Math.max(vp.width,vp.height)),v=pg.getViewport({scale:2*scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await pg.render({canvasContext:c.getContext('2d'),viewport:v}).promise;blobs.push(await toBlob(c,.92))}}else if(f.type.startsWith('image/'))blobs.push(f)}await B().addPageBlobs(blobs,B().summary().page+1);progress(`Přidáno ${blobs.length} stránek. ✅`);await render()}catch(e){console.error(e);progress('Přidání selhalo: '+(e.message||e))}finally{busy=false}}
function progress(t){const e=$('#pageProgress');if(e)e.textContent=t}
function luma(r,g,b){return .2126*r+.7152*g+.0722*b}
function sampleCanvas(src,max=520){const sc=Math.min(1,max/Math.max(src.width,src.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(src.width*sc));c.height=Math.max(1,Math.round(src.height*sc));c.getContext('2d').drawImage(src,0,0,c.width,c.height);return c}
function detectPaper(src){const c=sampleCanvas(src,480),x=c.getContext('2d'),d=x.getImageData(0,0,c.width,c.height).data,w=c.width,h=c.height;let border=0,bn=0,center=0,cn=0;const m=Math.max(2,Math.round(Math.min(w,h)*.06));for(let y=0;y<h;y+=2)for(let xx=0;xx<w;xx+=2){const i=(y*w+xx)*4,L=luma(d[i],d[i+1],d[i+2]);if(xx<m||xx>=w-m||y<m||y>=h-m){border+=L;bn++}if(xx>w*.25&&xx<w*.75&&y>h*.25&&y<h*.75){center+=L;cn++}}border/=bn||1;center/=cn||1;if(center-border<14)return null;const th=border+(center-border)*.42,row=new Float32Array(h),col=new Float32Array(w);for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++){const i=(y*w+xx)*4;if(luma(d[i],d[i+1],d[i+2])>th){row[y]++;col[xx]++}}let top=0,bottom=h-1,left=0,right=w-1;while(top<h&&row[top]/w<.34)top++;while(bottom>top&&row[bottom]/w<.34)bottom--;while(left<w&&col[left]/h<.34)left++;while(right>left&&col[right]/h<.34)right--;const bw=right-left+1,bh=bottom-top+1,area=bw*bh/(w*h);if(area<.38||area>.995)return null;const sx=src.width/w,sy=src.height/h,pad=.012;return {x:Math.max(0,(left/w-pad)*src.width),y:Math.max(0,(top/h-pad)*src.height),w:Math.min(src.width,(bw/w+pad*2)*src.width),h:Math.min(src.height,(bh/h+pad*2)*src.height)}}
async function smartCrop(i){const m=B().pageMeta()[i];if((m.ocrDone||m.edits)&&!confirm('Auto ořez resetuje OCR a textové úpravy této stránky. Pokračovat?'))return;busy=true;progress('Hledám okraje papíru…');try{const src=await blobCanvas(await B().pageBlob(i)),r=detectPaper(src);if(!r){progress('Okraje papíru nejdou bezpečně určit. Stránku jsem nechal beze změny.');return}const c=document.createElement('canvas');c.width=Math.round(r.w);c.height=Math.round(r.h);c.getContext('2d').drawImage(src,r.x,r.y,r.w,r.h,0,0,c.width,c.height);await B().replacePageBlob(i,await toBlob(c),{resetGeometry:true,message:'Stránka automaticky oříznuta.'});progress('Auto ořez hotový. ✅');await render()}catch(e){progress('Auto ořez selhal: '+(e.message||e))}finally{busy=false}}
function skewScore(src,angle){const c=sampleCanvas(src,600),out=document.createElement('canvas');out.width=c.width;out.height=c.height;const x=out.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,out.width,out.height);x.save();x.translate(out.width/2,out.height/2);x.rotate(angle*Math.PI/180);x.drawImage(c,-c.width/2,-c.height/2);x.restore();const d=x.getImageData(0,0,out.width,out.height).data,rows=new Float32Array(out.height);for(let y=0;y<out.height;y+=2)for(let xx=0;xx<out.width;xx+=2){const i=(y*out.width+xx)*4;if(luma(d[i],d[i+1],d[i+2])<145)rows[y]++}let s=0;for(let y=2;y<rows.length;y+=2){const q=rows[y]-rows[y-2];s+=q*q}return s}
async function deskew(i){const m=B().pageMeta()[i];if((m.ocrDone||m.edits)&&!confirm('Narovnání resetuje OCR a textové úpravy této stránky. Pokračovat?'))return;busy=true;progress('Měřím sklon textu…');try{const src=await blobCanvas(await B().pageBlob(i));let best=0,score=-1;for(let a=-4;a<=4;a+=.5){const s=skewScore(src,a);if(s>score){score=s;best=a}}if(Math.abs(best)<.4){progress('Stránka už vypadá rovně. ✅');return}const rad=best*Math.PI/180,cos=Math.abs(Math.cos(rad)),sin=Math.abs(Math.sin(rad)),c=document.createElement('canvas');c.width=Math.ceil(src.width*cos+src.height*sin);c.height=Math.ceil(src.width*sin+src.height*cos);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.translate(c.width/2,c.height/2);x.rotate(rad);x.drawImage(src,-src.width/2,-src.height/2);await B().replacePageBlob(i,await toBlob(c),{resetGeometry:true,message:`Stránka narovnána o ${best.toFixed(1)}°.`});progress(`Narovnáno o ${best.toFixed(1)}°. ✅`);await render()}catch(e){progress('Narovnání selhalo: '+(e.message||e))}finally{busy=false}}
function stats(c){const s=sampleCanvas(c,500),d=s.getContext('2d').getImageData(0,0,s.width,s.height).data;let mr=0,mg=0,mb=0,ml=0,n=0;for(let i=0;i<d.length;i+=16){mr+=d[i];mg+=d[i+1];mb+=d[i+2];ml+=luma(d[i],d[i+1],d[i+2]);n++}mr/=n;mg/=n;mb/=n;ml/=n;let vv=0;for(let i=0;i<d.length;i+=16){const q=luma(d[i],d[i+1],d[i+2])-ml;vv+=q*q}return {r:mr,g:mg,b:mb,l:ml,sd:Math.sqrt(vv/n)||1}}
function matchCanvas(src,a,b){const c=document.createElement('canvas');c.width=src.width;c.height=src.height;const x=c.getContext('2d');x.drawImage(src,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data,k=Math.max(.65,Math.min(1.55,a.sd/b.sd));for(let i=0;i<d.length;i+=4){d[i]=Math.max(0,Math.min(255,a.r+(d[i]-b.r)*k));d[i+1]=Math.max(0,Math.min(255,a.g+(d[i+1]-b.g)*k));d[i+2]=Math.max(0,Math.min(255,a.b+(d[i+2]-b.b)*k))}x.putImageData(im,0,0);return c}
async function matchAll(){if(busy)return;busy=true;try{const ref=+$('#pageStyleRef').value,meta=B().pageMeta();progress(`Analyzuju vzorovou stranu ${ref+1}…`);const rc=await blobCanvas(await B().pageBlob(ref)),rs=stats(rc);for(let i=0;i<meta.length;i++){if(i===ref)continue;progress(`Sjednocuju stranu ${i+1}/${meta.length}…`);const c=await blobCanvas(await B().pageBlob(i)),mc=matchCanvas(c,rs,stats(c));await B().replacePageBlob(i,await toBlob(mc,.94),{resetGeometry:false,message:`Vzhled strany ${i+1} sjednocen podle strany ${ref+1}.`})}progress('Vzhled stránek sjednocen. ✅');await render()}catch(e){console.error(e);progress('Sjednocení selhalo: '+(e.message||e))}finally{busy=false}}
function open(){build();sheet.classList.remove('hidden');document.body.style.overflow='hidden';render()}
function close(){sheet?.classList.add('hidden');document.body.style.overflow='';revoke()}
async function init(){for(let i=0;i<100&&!B();i++)await new Promise(r=>setTimeout(r,50));build();window.PDFPPageTools={open,close,render};const pager=$('.pager');if(pager&&!$('#pageToolsPager')){const b=document.createElement('button');b.id='pageToolsPager';b.className='ghost';b.textContent='🗂';b.title='Správa stránek';b.onclick=open;pager.appendChild(b)}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();